name: Generate GitHub 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D GitHub Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: varad-kulkarni172

      - name: Check directory contents
        run: ls -R

      - name: Move output to docs
        run: |
          mkdir -p docs
          cp -r profile-3d-contrib/* docs/


      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Auto-update 3D contribution graph" || echo "No changes to commit"
          git push
